### ISSUE TITLE
Support of the training-independent inference script with pre-trained model

### ISSUE THREAD

**Issue by rose-jinyang** [VITA-Group/FasterSeg#43]
Hello
How are you?
Thanks for contributing this project.
I think that the inference with pre-trained model is dependent on training dataset.
Could u provide an independent script for test inference?
Thanks.

**Comment by chenwydj** [comment]
Hi @rose-jinyang! Thank you for your interest in our work!

Please see the configurations [here](https://github.com/VITA-Group/FasterSeg/blob/master/train/config_train.py#L107) to switch to either evaluation (compute mIoU against your ground truth) or test (no ground truth available, just output the prediction files).
