### ISSUE TITLE
How can FasterSeg be used to perform inference on a video?

### ISSUE THREAD

**Issue by Gaussianer** [VITA-Group/FasterSeg#47]
Hello,

how can I run the inference of FasterSeg on a video?

I saw that you created the gif  in the readme using a [script](https://github.com/VITA-Group/FasterSeg/issues/23#issuecomment-598571154). Did you use the [tester.py](https://github.com/VITA-Group/FasterSeg/blob/master/tools/engine/tester.py) script for this?
If so, how do you use this script?  

Best regards

**Comment by chenwydj** [comment]
Hi @Gaussianer,

Thank you for your interest in our work!

You can generate the RBG predictions by setting `show_prediction=True` in [`train.py`](https://github.com/VITA-Group/FasterSeg/blob/master/train/train.py#L139).

For the gif, I just made predictions to all frames of the video, and concatenated them into a gif.

**Comment by Gaussianer** [comment]
Thanks @chenwydj for your reply!

I need a script that does the inference on a video. Do I have to write my own script for this?

Best regards

**Comment by chenwydj** [comment]
Hi @Gaussianer,

Sorry I did not save that command. As I remember I used `ffmpeg` command line tool to chunk the video into frames and to make the gif.

**Comment by Gaussianer** [comment]
Hi @chenwydj ,

All right, thanks.
I would like to apply the inference of FasterSeg to a video camera in real time. 
So I think I will have to write my own script for this?

The gif does not really play a role in my project. I just thought that you used a video for this. That would have saved me a little work.

**Comment by chenwydj** [comment]
Hi @Gaussianer,

You are right, and unfortunately, we did not prepare scripts for videos.

**Comment by Gaussianer** [comment]
Hi @chenwydj,

All right. Thanks for your quick answers :-)
