### ISSUE TITLE
I reported an error on my own data set while I was infering

### ISSUE THREAD

**Issue by mx1mx2** [VITA-Group/FasterSeg#48]
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 19 and 20 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:71

Best regards

**Comment by chenwydj** [comment]
Hi @mx1mx2,

Thank you for your interest in our work!

1. Which script was this error coming from?
2. What is the size of your image?
3. What is the crop size you used for training?

**Comment by mx1mx2** [comment]
thank you very much,i have solved it.

another question,how do i get my datasets `latency_lookup_table.npy`?
Best regards

**Comment by mx1mx2** [comment]
Thank you very much,i have solved it .

when i go to the second workflow  of _search the architecture_, the following error occur.
[TensorRT] ERROR: Network must have at least one output

Best regards

**Comment by chenwydj** [comment]
Hi @mx1mx2,

Please take a look at [this section](https://github.com/VITA-Group/FasterSeg#52-generate-the-latency-lookup-table).

Basically, you need to update the H and W [here](https://github.com/VITA-Group/FasterSeg/blob/master/latency/latency_lookup_table.py#L7).

For the TensorRT error, I never met this before. Could you provide more error messages?
