### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by hitsz-zuoqi** [VITA-Group/FasterSeg#49]
Hello. I'm try to do training,validate and test. The first two process work well but when I modify the C.is_eval = True.
The error will be :
**Traceback (most recent call last):
  File "train.py", line 295, in <module>
    main()
  File "train.py", line 82, in main
    train_loader = get_train_loader(config, Cityscapes, test=config.is_test)
  File "/opt/data/private/FasterSeg-master/train/dataloader.py", line 52, in get_train_loader
    train_dataset = dataset(data_setting, "train", train_preprocess, config.batch_size * config.niters_per_epoch)
  File "../tools/datasets/BaseDataset.py", line 23, in __init__
    self._file_names = self._get_file_names(split_name)
  File "../tools/datasets/BaseDataset.py", line 80, in _get_file_names
    with open(source) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/data/private/FasterSeg-master/tools/datasets/cityscapes/cityscapes_train_val_fine.txt'**

I open the dir and find there is no such file, does it mean that I should merge the trainset and valset for training?
Could you help me? Thank you!

**Comment by chenwydj** [comment]
Hi @hitsz-zuoqi!

Thank you for your interest in our work!

`cityscapes_train_val_fine.txt` is just a concatenation of `cityscapes_train_fine.txt` and `cityscapes_val_fine.txt`

It is for final testing on Cityscapes online leaderboard. Usually when people want to make perditions for the test data and submit online, they train a model with both training and validation images.
