### ISSUE TITLE
CUDA out of memory: GeForce GTX 1650.

### ISSUE THREAD

**Issue by TamuseDomain** [VITA-Group/FasterSeg#56]
Hi!
Thank you Wuyang, Xinyu, Xianming, Qian, Yuan and Zhangyang, for sharing your great work.

I'm trying your project, but at <<train_search.py>>, I get the following error:

![image](https://user-images.githubusercontent.com/30960795/104520922-2d2a7500-55b9-11eb-84db-a8d49f4a7c54.png)

I'm running on: 
Ubuntu 18.04.5 LTS 
Dell G3 3590
Core Intel i5-9300H 
8 GB RAM
NVIDIA GeForce GTX 1650 (4GB graphic memory)

I already tried turning down the batch size, crop size and even the number of workers.
Could the GeForce be able to run this work, or do I need a more capable GPU (>= 11G graphic memory)?

Thank you again!

**Comment by chenwydj** [comment]
Hi @TamuseDomain!

Thank you for your interest in our work!

We did not try our code on GTX 1650. I think capable GPU memory is required.
