### ISSUE TITLE
Which Nvidia GPU card do you use for training?

### ISSUE THREAD

**Issue by Jun-jieChen** [VITA-Group/FasterSeg#58]
Hey, author!
I would like to ask which Nvidia GPU card do you use for training?
and How many cards do you use?

**Comment by chenwydj** [comment]
Hi @Jun-jieChen ,

Thank you for your interest in our work!

Please take a look at our prerequisites here: https://github.com/VITA-Group/FasterSeg#prerequisites

**Comment by Jun-jieChen** [comment]
@chenwydj 
Thanks, but I don't know how many GPUs for training. The prerequeisties contains `>=11G graphic memory` , it means I need only one 11G Nvidia GPU for training?
